# Generated by Django 2.0.13 on 2019-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('slope', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
