# Generated by Django 2.0.13 on 2019-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
